### ISSUE TITLE
AttributeError: 'CountryField' object has no attribute 'db_collation' when upgrading Django from 3.0 to 3.2.16

### ISSUE THREAD

**Issue by IRunac** [SmileyChris/django-countries#417]
Hello, I've read closed issues on this topic and while it seemed that this issue was resolved in django-countries 7.1, I'm still getting this error on django-countries v7.5

`File "/home/ubuntu/python/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle post_migrate_state = executor.migrate( File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial) File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial) File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration state = migration.apply(state, schema_editor) File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/migration.py", line 116, in apply operation.state_forwards(self.app_label, project_state) File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/operations/models.py", line 80, in state_forwards state.add_model(ModelState( File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 95, in add_model self.reload_model(app_label, model_name) File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 156, in reload_model self._reload(related_models) File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 189, in _reload self.apps.render_multiple(states_to_be_rendered) File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 305, in render_multiple model.render(self) File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 565, in render body = {name: field.clone() for name, field in self.fields.items()} File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/migrations/state.py", line 565, in <dictcomp> body = {name: field.clone() for name, field in self.fields.items()} File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 512, in clone name, path, args, kwargs = self.deconstruct() File "/home/ubuntu/python/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1089, in deconstruct if self.db_collation: AttributeError: 'CountryField' object has no attribute 'db_collation'`

**Comment by IRunac** [comment]
It seems someone else was also still having this issue on v7.2 
[#354](https://github.com/SmileyChris/django-countries/issues/354#issuecomment-1050694629)

**Comment by IRunac** [comment]
Ah, nevermind, before we were using this library, we had our own custom field that was also called CountryField, and it was giving the same error on our first migration. Closing :)
