### ISSUE TITLE
TypeError: 'type' object is not subscriptable 

### ISSUE THREAD

**Issue by bruecksen** [SmileyChris/django-countries#369]
I get an error with the newest django-countries version 7.3 in my python 3.8 environment:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/pretix/venv/lib/python3.8/site-packages/pretix/__main__.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/pretix/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/var/pretix/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/var/pretix/venv/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/pretix/venv/lib/python3.8/site-packages/django_countries/__init__.py", line 66, in <module>
    class Countries(CountriesBase):
  File "/var/pretix/venv/lib/python3.8/site-packages/django_countries/__init__.py", line 380, in Countries
    ) -> set[str]:
TypeError: 'type' object is not subscriptable
```

**Comment by ajaykarthikr** [comment]
I am facing the same error in version 7.3 and python 3.8 environment.

**Comment by smokephil** [comment]
here the same. It should work with python 3.9

**Comment by Shaphil** [comment]
Same here. Not working with Python 3.6, 3.7 or 3.8 but it works with 3.9.

**Comment by forrestkouakou** [comment]
Same here. It's going mad when I use `country_dict=True` 
Django 4.0.2
DRF 3.13.1

**Comment by saemideluxe** [comment]
Same problem here. This happend after the last release. There is now already a PR, but one option would also be to add ```python_requires='>3.5.2',``` and replace the current release.

Great library btw, thanks.

**Comment by SmileyChris** [comment]
Thanks for the report, fixed and released as v7.3.1

**Comment by forrestkouakou** [comment]
It's weir but I still struggling with the `country_dict` parameter. I still can't use it with DRF
Error: `Error occurred during checks: TypeError("__init__() got an unexpected keyword argument 'country_dict'")
`
Django version 4.0.2
DRF 3.13.1
Python 3.8.10
