### ISSUE TITLE
Support for django 3.2 

### ISSUE THREAD

**Issue by nasir733** [SmileyChris/django-countries#345]
`  File "C:\codingProjects\LokknaBackend\manage.py", line 22, in <module>
    main()
  File "C:\codingProjects\LokknaBackend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\management\commands\migrate.py", line 75, in handle
    self.check(databases=[database])
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\management\base.py", line 419, in check
    all_issues = checks.run_checks(
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\core\checks\model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\db\models\base.py", line 1271, in check
    *cls._check_fields(**kwargs),
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\db\models\base.py", line 1380, in _check_fields
    errors.extend(field.check(**kwargs))
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django_countries\fields.py", line 283, in check
    errors = super().check(**kwargs)
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1013, in check
    *self._check_db_collation(databases),
  File "C:\codingProjects\LokknaBackend\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1045, in _check_db_collation
    self.db_collation is None or
AttributeError: 'CountryField' object has no attribute 'db_collation'`

getting this error in django 3.2 works fine in django 3.1

**Comment by nasir733** [comment]
@SmileyChris  any update !!!

**Comment by SmileyChris** [comment]
Version 7.1 (released 17 March 2021) has 3.2 support. Are you sure you've updated to this version? If so, feel free to reopen this issue.
